name: HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
