name: Feature request
description: Stel een verbetering voor Dummy OS EMS voor.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: goal
    attributes:
      label: Doel
      description: Welk probleem of welke behoefte moet hiermee worden opgelost?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Voorstel
      description: Beschrijf de gewenste oplossing.
    validations:
      required: true
